CREATE TABLE credit_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   credit_code UUID NOT NULL,
   credit_value DECIMAL NOT NULL,
   day_first_installment date NOT NULL,
   number_installments INT NOT NULL,
   status INT,
   customer_id BIGINT,
   CONSTRAINT pk_credit_table PRIMARY KEY (id)
);

ALTER TABLE credit_table ADD CONSTRAINT uc_credit_table_creditcode UNIQUE (credit_code);

ALTER TABLE credit_table ADD CONSTRAINT FK_CREDIT_TABLE_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer_table (id);